### ISSUE TITLE
Height of the lines

### ISSUE THREAD

**Issue by nippotam** [braitsch/ofxParagraph#1]
The draw() updates the paragraph when you change the size of the letter, but it changes only the number of work per line not the height of the line.
here are two example at police size 22
![capture_d_ecran_10_06_2015_20_03](https://cloud.githubusercontent.com/assets/4741789/8090037/dc370f9a-0fab-11e5-8675-e0980d29718a.png)

at police size 11

![capture_d_ecran_10_06_2015_20_04](https://cloud.githubusercontent.com/assets/4741789/8090050/ef4692ae-0fab-11e5-8399-e50ab3ae3d2c.png)

**Comment by nippotam** [comment]
I discover what I need : set leading. I probably need to document roughly the addons.

thanks @braitsch &apologizes

**Comment by braitsch** [comment]
I've thought about auto calculating the leading based on the font size but figured most people would rather dial in that value manually.

**Comment by nippotam** [comment]
Yes it is probably the best way even it is not usual in text tools such a indesign. But we are in C++ there. In my case I just put the font height + some pixels in the leading.
