### ISSUE TITLE
crashes if width is too small

### ISSUE THREAD

**Issue by ofZach** [braitsch/ofxParagraph#5]
in the demo example if you set the width of a paragraph to a small amount it crashes...  maybe there's some logic issues that need to be resolved with line breaking?  

thanks for this addon and the smart font addon !

**Comment by braitsch** [comment]
What width are you setting it to? If I set the width of the first paragraph to zero it still runs fine.

```
int x = (ofGetWidth() - tWidth)/2;
for (int i=0; i<paragraphs.size(); i++){
    paragraphs[i]->setWidth(pWidth);
    paragraphs[i]->setLeading(pLeading);
    paragraphs[i]->setSpacing(pFontSize*.7);
    paragraphs[i]->setBorderPadding(30);
    paragraphs[i]->setPosition(x+((pWidth+pPadding)*i), ofGetHeight()/2 - paragraphs[0]->getHeight()/2);
}
// setting width to zero for testing purposes //
    paragraphs[0]->setPosition(100, 100);
    paragraphs[0]->setWidth(0);
```

<img width="175" alt="screen shot 2016-10-01 at 8 43 18 pm" src="https://cloud.githubusercontent.com/assets/144289/19018468/bc14cb86-8817-11e6-9be3-2b80f348bd7a.png">

**Comment by ofZach** [comment]
this crashes for me: 

```
for (int i=0; i<paragraphs.size(); i++){
    paragraphs[i]->setWidth(MAX(mouseX, 0));
}
```

in draw() when mouse is low, or zero

stacktrace if helpful 

<img width="1251" alt="screen shot 2016-10-01 at 11 49 46 pm" src="https://cloud.githubusercontent.com/assets/142897/19018503/c7b0fb08-8831-11e6-8cff-1ab688c70b2b.png">

**Comment by braitsch** [comment]
Oof, are you running that inside of a mouseMoved function? That could be a problem...

**Comment by braitsch** [comment]
Interesting. It looks like the issue is related to the font file. In the example, the third paragraph uses `Raleway-SemiBoldItalic.ttf` which when resized down causes the app to crash. The other two fonts appear to be fine. Are you seeing the same thing?

```
void ofApp::mouseMoved(int x, int y )
{
    for (int i=0; i<paragraphs.size(); i++){
        paragraphs[2]->setWidth(MAX(x, 0));
    }
}
```
